name: 🐛 Bug Report
description: Report a bug or unexpected behavior in DAFU fraud detection platform
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in DAFU! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Affected Component
      description: Which component of DAFU is affected?
      options:
        - Fraud Detection Models (Isolation Forest, LSTM/GRU)
        - API Services (Fraud Scoring, Batch Processing, Model Management)
        - Feature Engineering Pipeline
        - Rules Engine
        - Model Persistence
        - Data Preprocessing
        - Visualization/Analytics
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic issue, minor inconvenience)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 10]
        - Python version: [e.g., 3.8.10, 3.9.7]
        - DAFU version: [e.g., v1.0.0, commit hash]
        - Dependencies: [e.g., TensorFlow 2.8.0, scikit-learn 1.0.2]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: 📋 Error Logs
      description: If applicable, add error logs or stack traces
      placeholder: |
        ```
        Paste error logs here
        ```
      render: shell

  - type: textarea
    id: sample-data
    attributes:
      label: 📊 Sample Data (if applicable)
      description: If the bug is related to data processing, provide sample data (anonymized)
      placeholder: |
        Provide sample CSV data or describe the data structure that causes the issue
      render: csv

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I understand this is a fraud detection platform and will not share sensitive data
          required: true
