# Prometheus Configuration for DAFU - Data Analytics Functional Utilities
# ========================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dafu-fraud-detection'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Fraud Detection API
  - job_name: 'fraud-detection-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fraud-detection-api:8000']
        labels:
          service: 'fraud-detection-api'
          environment: 'development'

  # PostgreSQL Database (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
    # Uncomment when postgres_exporter is added

  # Redis Cache (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
    # Uncomment when redis_exporter is added

  # RabbitMQ Message Broker
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'
    # RabbitMQ Prometheus plugin must be enabled

  # Celery Workers (requires celery-exporter)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']
        labels:
          service: 'celery-workers'
    # Uncomment when celery-exporter is added
